//teste do RES
##################################################################
@baseURL = http://localhost:4000
//GET- LISTA OS FUNCIONARIOS
GET {{baseURL}}/funcionarios


//GET- ID
GET {{baseURL}}/funcionarios/{{id}}
Content-Type: application/json
@id = 615b661c2c3081548ebd2645

##################################################################
// POST INCLUI NOVO FUNCIONARIO
POST {{baseURL}}/funcionarios
Content-Type: application/json

{
    "nome": "Clara Lima",
    "status":"proprio",
    "idade":"23",
    "cargo": "Analista",
    "salario":"3000"
}
##################################################################

// PUT // ALTERA OS DADOS DO FUNCIONARIO
PUT  {{baseURL}}/funcionarios
Content-Type: application/json

{
    "_id":"615b573e640d7f9eceb73c15",
    "nome": "Luis Santos ",
    "status":"proprio",
    "idade":"23",
    "cargo": "Analista",
    "salario":"3000"
}
##################################################################

//DELETE apaga os dados do funcionario pelo ID


DELETE   {{baseURL}}/funcionarios/{{id}}
Content-Type: application/json

@id = 615b52a43570692281e07f33